### PR TITLE
Update project.md

### PR DESCRIPTION
**Pull request by garrettstarwars**

### CODE REVIEW

**Comment by garrettstarwars** [comment]
My idea for a website that would solve a problem facing teenagers on Vancouver Island is a website that would list intern, volunteer, and job opportunities for jobs in different lines of work. One would input a line of work they are interested in and the website would direct them to various internship/career/volunteer opportunities for companies in those lines of work.

**Review by FlyteWizard — APPROVED** [review]
Remember you can edit files in the browser with GitHub. 

Resource: https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by FlyteWizard** [comment]
Hey Garrett!

This is a really neat project idea. There are plenty of job websites, but none of them cater to teenagers.

**Comment by FlyteWizard** [comment]
We won't be merging Pull Request on this Repository. Since everyone edited the same file.

**Pull request closed without merging**
